# Generated by Django 3.1.7 on 2021-03-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates that this user has permissions to make transactions.'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('std', models.CharField(max_length=5)),
                ('tokens', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
