# Generated by Django 3.1.7 on 2021-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210326_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
