# Generated by Django 3.1.7 on 2021-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210326_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tokens',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
