# Generated by Django 3.2.4 on 2021-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210421_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcode'),
        ),
    ]
