# Generated by Django 3.2.4 on 2021-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
