# Generated by Django 3.2.7 on 2021-10-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('canteen', 'Canteen'), ('stationary', 'Stationary'), ('transportation', 'Transportation')], default='category', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calorie',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie', to='core.product'),
        ),
    ]
