# Generated by Django 3.1.7 on 2021-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210324_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ManyToManyField(related_name='transaction', to='core.Product'),
        ),
    ]
