# Generated by Django 3.1.7 on 2021-03-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bought_by',
        ),
    ]
