# Generated by Django 3.1.7 on 2021-03-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210326_1800'),
        ('core', '0007_remove_transaction_bought_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bought_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
