# Generated by Django 3.2.7 on 2021-11-11 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resetcredentialtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Pin must be of 6 digits', regex='^[0-9]{6,6}$')]),
        ),
    ]
