# Generated by Django 3.2.7 on 2021-11-11 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_resetcredentialtoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.CharField(blank=True, max_length=127, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Pin must be of 6 digits', regex='^[0-9]{6,6}$')]),
        ),
    ]
