# Generated by Django 3.2.7 on 2021-10-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_id_disabled',
            field=models.BooleanField(default=False, verbose_name='ID Disabled'),
        ),
        migrations.AddField(
            model_name='student',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
