# Generated by Django 3.2.7 on 2021-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210922_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('staff', 'STAFF'), ('student', 'STUDENT'), ('manager', 'MANAGER')], default='student', max_length=15),
        ),
    ]
